project:
  type: book
  output-dir: _book

execute:
  freeze: auto

book:
  title: "Land in the Earth System"
  subtitle: "Introducing global patterns, processes, and underlying principles for how climate shapes the terrestrial biosphere and how land feeds back to Earth system dynamics."
  author: "Benjamin Stocker"
  date: "2024/02/20"
  page-navigation: true
  chapters:
    - index.qmd
    - intro.qmd
    - biogeography.qmd
    - globalcarbonbudget.qmd
    - gpp.qmd
    - ecosystemcarbon.qmd
    - globalcarbonpatterns.qmd
    - landclimate.qmd
    - ecohydrology.qmd
    - nutrients.qmd
    - ghg.qmd
    - oceancarbon.qmd
    - globenvchange.qmd
    - feedbacks.qmd
    - landusechange.qmd
    - researchtools.qmd
    - reading.qmd
    - references.qmd
  favicon: "figures/favicon.ico"
  twitter-card: true
  search: true
  repo-url: https://github.com/geco-bern/les_i/
  sharing: [twitter, facebook]
  navbar:
    title: " "
    logo: "images/logo.png"
    background: "#3A3A3A"
    search: true
    right:
      - text: "Home"
        file: index.qmd

bibliography: references.bib

format:
  html:
    theme: 
      light: [cosmo, theme-light.scss]
      dark: [cosmo, theme-dark.scss]
